server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.we_are_team.school_background_service_system.pojo
#  type-aliases-package: com.we_are_team.school_background_service_system.mybatis.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

spring:
 datasource:
     url: jdbc:mysql://localhost:3306/campus_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
     username: root
     password: fwc15819541578
     driver-class-name: com.mysql.cj.jdbc.Driver

# token秘钥以及过期时间
we:
 jwt:
   user-secret-key: weareteam
   user-ttl: 72000000
   user-token-name: token
 alioss:
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5tEUyi76UvK181VRECDu
  access-key-secret: nF60yJIplDFqNmtdRxgnyX6R773tC2
  bucket-name: shcoolsystem
