server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.we_are_team.school_background_service_system.pojo
  #  type-aliases-package: com.we_are_team.school_background_service_system.mybatis.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

thymeleaf:
  prefix: classpath:/templates/ #指定thymeleaf模板前缀目录
  suffix: .html #指定模板的后缀
  cache: false #是否开启thymeleaf缓存 默认值是true开启缓存  在开发过程中推荐使用false
  mode: HTML5 #指定模板模式
  encoding: UTF-8 #指定模板编码

# token秘钥以及过期时间
we:
  # 用户端jwt令牌秘钥
  jwt:
    user-secret-key: weareteam
    user-ttl: 72000000000
    user-token-name: token
    admin-secret-key: teamarewe
    admin-ttl: 72000000000
    admin-token-name: admintoken
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEUyi76UvK181VRECDu
    access-key-secret: nF60yJIplDFqNmtdRxgnyX6R773tC2
    bucket-name: shcoolsystem
#分页查询插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
